name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  tag: 0.1  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo "img_name=${{ secrets.DOCKERHUB_USERNAME }}/srst2env" >> "$GITHUB_ENV"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.img_name }}:latest,${{ env.img_name }}:${{ env.tag }}          
